first-commits: Initialize AMI with base Windows Server 2022
cisagov/windows-commando-vm-packer pull request #5
Opened 2022-05-19 05:10 UTC by itsmostafa

Initialize project with a base windows image and a bootstrap winrm file for packer to be able to connect to the instance via WinRM.

## 🗣 Description ##
This PR only contains the base Windows Server 2022 image for initializing the project.
The Windows Administrator password for this AMI is set by AWS SSM Parameter Store.

## 💭 Motivation and context ##
This project can eventually be used to be able to create machine images of Windows Commando VM.

## 🧪 Testing ##
Need to have repository secrets set.

## ✅ Pre-approval checklist ##

- [x] This PR has an informative and human-readable title.
- [x] Changes are limited to a single goal - *eschew scope creep!*
- [x] *All* future TODOs are captured in issues, which are referenced in code comments.
- [x] All relevant type-of-change labels have been added.
- [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [x] All relevant repo and/or project documentation has been updated to reflect the changes in this PR.
- [x] All new and existing tests pass.

2022-05-23 20:56 UTC, dav3r requested changes
This looks mostly good to me, but I noted a few things that should be fixed.  Also, please make sure that any late-breaking changes in https://github.com/cisagov/windows-server-packer/pull/10 get mirrored here.

2022-05-23 20:56 UTC, dav3r commented on .github/CODEOWNERS
> +* @dav3r @felddy @jsf9k @mcdonnnj @itsmostafa @xlyk
Alphabetize these:
```suggestion
* @dav3r @felddy @itsmostafa @jsf9k @mcdonnnj @xlyk
```

2022-05-23 20:56 UTC, dav3r commented on CONTRIBUTING.md
> +issue](https://github.com/cisagov/windows-commando-packer/issues) in this
This should match the repo name:
```suggestion
issue](https://github.com/cisagov/windows-commando-vm-packer/issues) in this
```

2022-05-23 20:56 UTC, dav3r commented on CONTRIBUTING.md
> +request](https://github.com/cisagov/windows-commando-packer/pulls), you will
Same as above:
```suggestion
request](https://github.com/cisagov/windows-commando-vm-packer/pulls), you will
```

2022-05-23 20:56 UTC, dav3r commented on CONTRIBUTING.md
> +pyenv local windows-commando-packer
Same as above:
```suggestion
cd windows-commando-vm-packer
pyenv virtualenv <python_version_to_use> windows-commando-vm-packer
pyenv local windows-commando-vm-packer
```

2022-05-23 20:56 UTC, dav3r commented on terraform-build-user/backend.tf
> +    key            = "windows-commando-packer/terraform-build-user.tfstate"
Match repo name:
```suggestion
    key            = "windows-commando-vm-packer/terraform-build-user.tfstate"
```

2022-05-23 20:56 UTC, dav3r commented on terraform-build-user/providers.tf
> +    Application = "windows-commando-packer"
Match repo name:
```suggestion
    Application = "windows-commando-vm-packer"
```

2022-05-23 20:56 UTC, dav3r commented on terraform-post-packer/main.tf
> +# The IDs of all cisagov/windows-commando-packer AMIs
Match repo name:
```suggestion
# The IDs of all cisagov/windows-commando-vm-packer AMIs
```

2022-05-23 20:56 UTC, dav3r commented on terraform-post-packer/main.tf
> +      "windows-server-2022-*-x86_64-ebs",
Reminder that this AMI pattern should change once we actually start installing Commando tools on here.

2022-05-23 20:56 UTC, dav3r commented on terraform-post-packer/main.tf
> +      "windows-server-2022-*-x86_64-ebs",
Reminder that this name should change once we actually start installing Commando tools on here.

2022-05-23 20:56 UTC, dav3r commented on src/packer.pkr.hcl
> +  ami_name                    = "windows-server-2022-${local.timestamp}-x86_64-ebs"
Reminder that the AMI name should change once we actually start installing Commando tools on here.

2022-05-23 20:56 UTC, dav3r commented on src/packer.pkr.hcl
> +    Application        = "Windows Server 2022"
We should use this tag to distinguish between AMIs created with this repo and those created by `cisagov/windows-server-packer`:
```suggestion
    Application        = "Windows Commando VM"
```

2022-11-11 18:05 UTC, closed without merging

2022-11-14 14:20 UTC, dav3r commented
@itsmostafa - Can you please elaborate on why you closed out this PR?

2022-11-14 16:04 UTC, itsmostafa commented
> @itsmostafa - Can you please elaborate on why you closed out this PR?

I went over this with Kyle on Friday, his last day, and was under the impression that this PR is very outdated and we should instead build on PR #21 . What are your thoughts?